### ISSUE TITLE
TypeError: Cannot read property 'room' of undefined

### ISSUE THREAD

**Issue by estiens** [sachinr/hubot-twitter-mention-script#1]
Anytime I try to deploy this I get the following error. I get it whether or not HUBOT_TWITTER_QUERY_ROOM is set, or I hardcode a room

**Comment by sarahjanebland** [comment]
Did you resolve this? I have the exact same problem

**Comment by estiens** [comment]
I honestly don't remember what I did to fix this particular problem, but this script is broken because it is using an old version of the twitter API. I wrote a script that does the same thing, but uses the new Twitter API here. https://github.com/estiens/hubot-twitter-mention-v2

**Comment by sarahjanebland** [comment]
Thanks. I submitted a PR on the env variable naming. I also discovered if you're using hubot with slack, the MENTION_ROOM variable being passed to `robot.messageRoom MENTION_ROOM, message` can't start with a '#' symbol
